# https://app.circleci.com/pipelines/github/allenalvin333/Learning/10/workflows/93d4af24-bfc8-4032-ba5a-8cbd641ef85f

version: 2.1                                      # CircleCI version

jobs:
  Build:                                          # Job name
    working_directory: ~/circleci-python          # Working directory
    docker:
      - image: "circleci/python:3.6.4"            # Docker image to be used
    steps:                                        # Steps to be executed
      - checkout                                  # Checkout the repository
      - run: python3 CI_CD/circleci/main.py       # Execute the main.py file
  Test:                                           # Job name
    working_directory: ~/circleci-python          # Working directory
    docker:
      - image: "circleci/python:3.6.4"            # Docker image to be used
    steps:                                        # Steps to be executed
      - checkout                                  # Checkout the repository
      - run: python3 CI_CD/circleci/test.py       # Execute the test.py file

workflows:                                        # Workflows to be executed
  Learn 0:                                        # Workflow name
    jobs:
      - Build:                                    # Job name
          requires: []                            # Dependencies
      - Test:                                     # Job name
          requires: [Build]                       # Dependencies          