version: 2.1

jobs:
  Build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 CI_CD/circleci/main.py
  Test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 CI_CD/circleci/test.py

workflows:
  Learn 8:
    jobs:
      - A:
          requires: []
      - B:
          requires: [A]