---                             # YAML document with Ansible Syntax
  - name: "Learn1"              # Ansible task name
    hosts: localhost            # Hosts to run the task on
    tasks:    
      - name: "Ping"            # Ansible task name
        ping:                   # Ansible task to ping server
      - name: "Stress"          # Ansible task name
        homebrew:               # Ansible task to stress server
          name: stress          # Name of the task
          state: present        # State of the task