name: Learn 3

on: push
env: 
  WORKSPACE_ENVIRONMENT_VARIABLE: "Allen's Workspace Environment Variable"

jobs:
  A:
    name: Python Syntax 
    runs-on: ubuntu-latest
    steps:
    - name: Check
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

  B:
    name: Apache Tomcat 
    runs-on: ubuntu-latest
    steps:
    - name: My Repository
      uses: actions/checkout@v2
      with:
        repository: allenalvin333/GFG_Learning 
        ref: master               
        path: ./CI_CD

    - name: Source Repository
      uses: actions/checkout@v2
      with:
        repository: apache/tomcat 
        ref: main               
        path: ./tomcat       

  C:
    name: Java Version 
    runs-on: ubuntu-latest
    steps:
    - name: Before
      run: java -version

    - name: Update
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'  
        java-package: jdk       
        architecture: x64        

    - name: After
      run: java -version

  D:
    name: Environment Variables
    runs-on: ubuntu-latest
    env:
      JOB_ENVIRONMENT_VARIABLE: "Allen's Job Environment Variable"

    steps:
    - name: Print
      env:
        STEP_ENVIRONMENT_VARIABLE: "${{ secrets.STEP_SECRET_VARIABLE }}"

      run: |
        echo ""
        echo "+------------------------------------------------------+"
        echo "| Accessing during runtime"
        echo "+------------------------------------------------------+"
        echo "| " $WORKSPACE_ENVIRONMENT_VARIABLE
        echo "| " $JOB_ENVIRONMENT_VARIABLE
        echo "| " $STEP_ENVIRONMENT_VARIABLE
        echo "+------------------------------------------------------+"
        echo "| Accessing using env context"
        echo "+------------------------------------------------------+"
        echo "|  ${{ env.WORKSPACE_ENVIRONMENT_VARIABLE }}"
        echo "|  ${{ env.JOB_ENVIRONMENT_VARIABLE }}"
        echo "|  ${{ env.STEP_ENVIRONMENT_VARIABLE }}"
        echo "+------------------------------------------------------+"