name: Learn 3

on: push

jobs:
  A:
    name: Python
    runs-on: ubuntu-latest
    steps:
    - name: Python Syntax Checker
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0

  B:
    name: Apache 
    runs-on: ubuntu-latest
    steps:
    - name: My Repo
      uses: actions/checkout@v2
      with:
        repository: allenalvin333/GFG_Learning 
        ref: master               
        path: ./CI_CD

    - name: Source Repo
      uses: actions/checkout@v2
      with:
        repository: apache/tomcat 
        ref: main               
        path: ./tomcat       

  C:
    name: Java
    runs-on: ubuntu-latest
    steps:
    - name: Before
      run: java -version

    - name: Update
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'  
        java-package: jdk       
        architecture: x64        

    - name: After
      run: java -version