name: Learn 5

on: push

env:
  APPLICATION_NAME: Allen

jobs:
  A:
    name: Requirements
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Python 
      uses: actions/setup-python@v2
    - name: Install Requirements
      run: pip install --quiet --requirement CI_CD/5/requirements.txt

    - name: Lint Code
      run: flake8 --ignore=E501,E231 CI_CD/5/*.py
    - name: Unit Tests
      run: python -m unittest --verbose --failfast     

  B:
    name: Build
    needs: [A]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up GCloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker
        gcloud info
    
    - name: Build and tag image
      run: docker build -t "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest" .
      
    - name: Push to GCP image registry
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest