name: Learn 7

on: [push]

jobs:
  Final:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Action
      uses: allenalvin333/GFG_Learning@custom
      with:
        entrypoint: /A/