name: Learn 7

on: push

jobs:
  none:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

# description: 'Creates releases based on a keyword'
# runs:
#    using: 'docker'
#    image: 'Dockerfile'
# branding:
#    icon: 'gift'
#    color: 'blue'
